name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  GITHUB_TOKEN: ${{ github.token }}
  CARGO_TERM_COLOR: always

jobs: 
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: moonrepo/setup-rust@v1
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all --check

      - uses: moonrepo/setup-rust@v1
        with:
          bins: cargo-make
          components: clippy
      - name: Run Clippy
        run: cargo make lint

      - uses: moonrepo/setup-rust@v1
        with:
          bins: cargo-make
          components: clippy
      - name: Run tests
        run: cargo make test

  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: freebsd
            os: ubuntu-latest
            target: x86_64-unknown-freebsd
          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build FreeBSD
        if: matrix.build == 'freebsd'
        uses: vmactions/freebsd-vm@v1
        with:
          release: "15.0"
          arch: x86_64
          usesh: true
          mem: 8192
          sync: rsync
          prepare: |
            pkg install -y rust
          run: |
            cargo build --release --locked
        
      - uses: moonrepo/setup-rust@v1
        if: matrix.build != 'freebsd'
        with:
          targets: ${{ matrix.target }}

      - name: Build
        if: matrix.build != 'freebsd'
        run: cargo build --release --locked